accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path('accounts/', include('accounts.urls')),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    CreateReceiptView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreate,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", CreateReceiptView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "categories/create/",
        ExpenseCategoryCreate.as_view(),
        name="create_category",
    ),
    path('accounts/create/', AccountCreateView.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)




# did my own research was able to get this code to work 
# would have to add authenticate to line 1 after login part of django.contrib.auth

# def signup(request):                 
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('home')
#     else:
#         form = UserCreationForm()
#     return render(request, 'signup.html', {'form': form}) --- context was just moved in example, since render expects the tree parameters 

receipts/views.py
from unicodedata import category
from django.shortcuts import redirect, render


from receipts.models import ExpenseCategory, Account, Receipt

from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView


# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class CreateReceiptView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expenses/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreate(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expenses/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")

receipts/templates/accounts/create.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
        <ul>
            {% if user.is_authenticated %}
                <li>
                <a href="{% url 'home' %}">Receipts</a>
             </li>
                <li>
                <a href="{% url 'logout' %}">Logout</a>
                </li>
                <li>
              <a href="{% url 'create_receipt' %}">Create receipt</a>
              </li>
              <li>
                <a href="{% url 'list_categories' %}">Categories</a>
                </li>
                <li>
                  <a href="{% url 'account_list' %}">Accounts</a>
                  </li>
                  <li>
                    <a href="{% url 'create_category' %}">Create category</a>
                    </li>
                    <li>
                      <a href="{% url 'create_account' %}">Create account</a>
                    </li>
            {% else %}
                <li>
                <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
              <a href="{% url 'login' %}">Login</a>
              </li>
            {% endif %}
        </ul>
    </nav>
  </header>
  <main>
        <div>
            <h1>Create account</h1>
            <form method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
            </form>
        </div>
  </main>
</body>

</html>

receipts/templates/accounts/list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
            <li>
            <a href="{% url 'home' %}">Receipts</a>
         </li>
            <li>
            <a href="{% url 'logout' %}">Logout</a>
            </li>
            <li>
          <a href="{% url 'create_receipt' %}">Create receipt</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Categories</a>
            </li>
            <li>
              <a href="{% url 'account_list' %}">Accounts</a>
              </li>
              <li>
                <a href="{% url 'create_category' %}">Create category</a>
                </li>
                <li>
                  <a href="{% url 'create_account' %}">Create account</a>
                </li>
        {% else %}
            <li>
            <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
          <a href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
    </ul>
    </nav>
  </header>
  <main>
    <h1>Accounts</h1>
    <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
          </tr>
        </thead>
        <tbody>
          {% for account in account_list %}
            <tr>
              <td>{{ account.name }}</td>
              <td>{{ account.number }}</td>
              <td>{{ account.receipts.all|length }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>



  </main>
</body>

</html>

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
        <li>
        <a href="{% url 'home' %}">Receipts</a>
        </li>
        <li>
          <a href="{% url 'logout' %}">Logout</a>
          </li>
          <li>
            <a href="{% url 'create_receipt' %}">Create receipt</a>
            </li>
            <li>
              <a href="{% url 'list_categories' %}">Categories</a>
              </li>
              <li>
                <a href="{% url 'account_list' %}">Accounts</a>
                </li>
                <li>
                  <a href="{% url 'create_category' %}">Create category</a>
                  </li>
                  <li>
                    <a href="{% url 'create_account' %}">Create account</a>
                  </li>
        {% else %}
        <li>
          <a href="{% url 'signup' %}">Sign Up</a>
          </li>
          <li>
            <a href="{% url 'login' %}">Login</a>
            </li>
        {% endif %}
      </ul>
      </nav>
    </header>
    <main>
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

receipts/templates/expenses/create.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
            <li>
            <a href="{% url 'home' %}">Receipts</a>
         </li>
            <li>
            <a href="{% url 'logout' %}">Logout</a>
            </li>
            <li>
          <a href="{% url 'create_receipt' %}">Create receipt</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Categories</a>
            </li>
            <li>
              <a href="{% url 'account_list' %}">Accounts</a>
              </li>
              <li>
                <a href="{% url 'create_category' %}">Create category</a>
                </li>
                <li>
                  <a href="{% url 'create_account' %}">Create account</a>
                </li>
        {% else %}
            <li>
            <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
          <a href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
    </ul>
    </nav>
  </header>
  <main>
    <div>
        <h1>Create Category</h1>
        <form method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
  </main>
</body>

</html>

receipts/templates/expenses/list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
            <li>
            <a href="{% url 'home' %}">Receipts</a>
         </li>
            <li>
            <a href="{% url 'logout' %}">Logout</a>
            </li>
            <li>
          <a href="{% url 'create_receipt' %}">Create receipt</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Categories</a>
            </li>
            <li>
              <a href="{% url 'account_list' %}">Accounts</a>
              </li>
              <li>
                <a href="{% url 'create_category' %}">Create category</a>
                </li>
                <li>
                  <a href="{% url 'create_account' %}">Create account</a>
                </li>
        {% else %}
            <li>
            <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
          <a href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
    </ul>
    </nav>
  </header>
  <main>
    <h1>Expense Categories</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of receipts</th>
    </tr>
  </thead>
  <tbody>
    {% for category in expensecategory_list %}
      <tr>
        <td>{{ category.name }}</td>
        <td>{{ category.receipts.all|length }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
  </main>
</body>

</html>

receipts/templates/receipts/create.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
            <li>
            <a href="{% url 'home' %}">Receipts</a>
         </li>
            <li>
            <a href="{% url 'logout' %}">Logout</a>
            </li>
            <li>
          <a href="{% url 'create_receipt' %}">Create receipt</a>
          </li>
          <li>
            <a href="{% url 'list_categories' %}">Categories</a>
            </li>
            <li>
              <a href="{% url 'account_list' %}">Accounts</a>
              </li>
              <li>
                <a href="{% url 'create_category' %}">Create category</a>
                </li>
                <li>
                  <a href="{% url 'create_account' %}">Create account</a>
                </li>
        {% else %}
            <li>
            <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
          <a href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
    </ul>
    </nav>
  </header>
  <main>
    <div>
        <h1>Create Receipt</h1>
    
        <form method="POST" enctype="multipart/form-data">
      
            <!-- Security token -->
            {% csrf_token %}
          
            <!-- Using the formset -->
            {{ form.as_p }}
              
            <button class="button">Create</button>
        </form>
    </div>
  </main>
</body>

</html>

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <header>
    <nav>
        <ul>
            {% if user.is_authenticated %}
                <li>
                <a href="{% url 'home' %}">Receipts</a>
             </li>
                <li>
                <a href="{% url 'logout' %}">Logout</a>
                </li>
                <li>
              <a href="{% url 'create_receipt' %}">Create receipt</a>
              </li>
              <li>
                <a href="{% url 'list_categories' %}">Categories</a>
                </li>
                <li>
                  <a href="{% url 'account_list' %}">Accounts</a>
                  </li>
                  <li>
                    <a href="{% url 'create_category' %}">Create category</a>
                    </li>
                    <li>
                      <a href="{% url 'create_account' %}">Create account</a>
                    </li>
            {% else %}
                <li>
                <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
              <a href="{% url 'login' %}">Login</a>
              </li>
            {% endif %}
        </ul>
    </nav>
  </header>
  <main>
    <h1>My Receipts</h1>
        
<table>
   <thead>
    <tr>
        <th>Vendor</th>
        <th>Total</th>
        <th>Tax</th>
        <th>Date</th>
        <th>Category</th>
        <th>Account</th>
    </tr>
   </thead>
   <tbody>
    {% for receipt in receipt_list %}
    <tr>

        <td>{{ receipt.vendor }}</td>
        <td>{{ receipt.total }}</td>
        <td>{{ receipt.tax }}</td>
        <td>{{ receipt.date }}</td>
        <td>{{ receipt.category }}</td>
        <td>{{ receipt.account }}</td>
    </tr>
    {% endfor %}
   </tbody>
</table>
  </main>
</body>

</html>